package exepciones.Trywithresources;

import java.io.IOException;

public class Main {
    public static void main(String[] args){
        try {
            Demo.verificarEdad(-4);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }


        try {
            Demo.start();
        } catch (IOException e) {
            System.out.println("Ocurri칩 un error: " +   e.getMessage()); // Esto si lo ver치 el usuario.
        }

        try {
            Demo.exceptionPersonalizada(-50);
        } catch (Throwable e) {
            System.out.println("Ocurri칩 un error: " +   e.getMessage()); // Esto si lo ver치 el usuario.
        }



    }
}
